import type { Category, CategorizeRule } from "./types.ts";

export const CATEGORIES: Category[] = [
  { id: "housing", name: "Housing", group: "living" },
  { id: "utilities", name: "Utilities", group: "living" },
  { id: "groceries", name: "Groceries", group: "living" },
  { id: "transport", name: "Transport", group: "living" },
  { id: "health", name: "Health", group: "living" },
  { id: "childcare", name: "Child care", group: "living" },
  { id: "dining", name: "Dining", group: "lifestyle" },
  { id: "coffee", name: "Coffee", group: "lifestyle" },
  { id: "shopping", name: "Shopping", group: "lifestyle" },
  { id: "personal-care", name: "Personal care", group: "lifestyle" },
  { id: "entertainment", name: "Entertainment", group: "lifestyle" },
  { id: "subscriptions", name: "Subscriptions", group: "lifestyle" },
  { id: "travel", name: "Travel", group: "lifestyle" },
  { id: "income", name: "Income", group: "income" },
  { id: "transfers", name: "Transfers", group: "money" },
  { id: "fees", name: "Fees & interest", group: "money" },
  { id: "other", name: "Other", group: "money" },
];

export const CATEGORY_BY_ID: Record<string, Category> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c]),
);

export const TRANSFER_CATEGORY = "transfers";
export const HOUSING_CATEGORY = "housing";
export const INCOME_CATEGORY = "income";

const DEFAULT_PATTERNS: Array<[string, string]> = [
  ["payroll", "income"],
  ["direct dep", "income"],
  ["direct deposit", "income"],
  ["salary", "income"],
  ["paycheck", "income"],
  ["interest posting", "income"],
  ["mortgage", "housing"],
  ["rocket mortgage", "housing"],
  ["rent", "housing"],
  ["apartments", "housing"],
  ["hoa", "housing"],
  ["state farm", "housing"],
  ["allstate", "housing"],
  ["homeowners", "housing"],
  ["pg&e", "utilities"],
  ["pge", "utilities"],
  ["pacific gas", "utilities"],
  ["comcast", "utilities"],
  ["xfinity", "utilities"],
  ["verizon", "utilities"],
  ["at&t", "utilities"],
  ["att", "utilities"],
  ["t-mobile", "utilities"],
  ["starlink", "utilities"],
  ["water dept", "utilities"],
  ["whole fds", "groceries"],
  ["whole foods", "groceries"],
  ["trader joe", "groceries"],
  ["safeway fuel", "transport"],
  ["safeway", "groceries"],
  ["kroger", "groceries"],
  ["costco", "groceries"],
  ["aldi", "groceries"],
  ["h-e-b", "groceries"],
  ["heb", "groceries"],
  ["ralphs", "groceries"],
  ["sprouts", "groceries"],
  ["instacart", "groceries"],
  ["grocery outlet", "groceries"],
  ["walmart", "groceries"],
  ["wm supercenter", "groceries"],
  ["shell oil", "transport"],
  ["shell", "transport"],
  ["chevron", "transport"],
  ["exxon", "transport"],
  ["conoco", "transport"],
  ["cardlock", "transport"],
  ["vehicle licensing", "transport"],
  ["uber", "transport"],
  ["lyft", "transport"],
  ["clipper", "transport"],
  ["parking", "transport"],
  ["jiffy lube", "transport"],
  ["o'reilly", "transport"],
  ["oreilly", "transport"],
  ["circle k", "transport"],
  ["76", "transport"],
  ["nanny", "childcare"],
  ["kaiser", "health"],
  ["cvs", "health"],
  ["walgreens", "health"],
  ["pharmacy", "health"],
  ["dental", "health"],
  ["starbucks", "dining"],
  ["mcdonald", "dining"],
  ["sweetgreen", "dining"],
  ["chipotle", "dining"],
  ["doordash", "dining"],
  ["uber eats", "dining"],
  ["papa murphy", "dining"],
  ["chick-fil-a", "dining"],
  ["chick fil a", "dining"],
  ["dairy queen", "dining"],
  ["tst", "dining"],
  ["dutch bros", "coffee"],
  ["amazon", "shopping"],
  ["amzn", "shopping"],
  ["target", "shopping"],
  ["nordstrom", "shopping"],
  ["ikea", "shopping"],
  ["homedepot", "shopping"],
  ["home depot", "shopping"],
  ["ace hardware", "shopping"],
  ["marshalls", "shopping"],
  ["ulta", "shopping"],
  ["old navy", "shopping"],
  ["oldnavy", "shopping"],
  ["ross stores", "shopping"],
  ["great clips", "personal-care"],
  ["netflix", "subscriptions"],
  ["spotify", "subscriptions"],
  ["apple.com/bill", "subscriptions"],
  ["icloud", "subscriptions"],
  ["google youtube", "subscriptions"],
  ["youtube", "subscriptions"],
  ["hulu", "subscriptions"],
  ["disney", "subscriptions"],
  ["united airlines", "travel"],
  ["delta air", "travel"],
  ["airbnb", "travel"],
  ["hilton", "travel"],
  ["marriott", "travel"],
  ["expedia", "travel"],
  ["steam", "entertainment"],
  ["steamgames", "entertainment"],
  ["payment thank you", "transfers"],
  ["ba electronic payment", "transfers"],
  ["online/mobile payment", "transfers"],
  ["credit crd", "transfers"],
  ["credit card payment", "transfers"],
  ["bank of america payment", "transfers"],
  ["online transfer", "transfers"],
  ["transfer to", "transfers"],
  ["transfer from", "transfers"],
  ["venmo", "transfers"],
  ["zelle", "transfers"],
  ["atm", "other"],
  ["monthly service charge", "fees"],
  ["interest charge", "fees"],
  ["interest charged", "fees"],
  ["annual fee", "fees"],
  ["overdraft", "fees"],
];

export function defaultRules(): CategorizeRule[] {
  return DEFAULT_PATTERNS.map(([pattern, categoryId], i) => ({
    id: `default-${i}`,
    pattern,
    categoryId,
    createdAt: 0,
    source: "default" as const,
  }));
}

export function categoryName(id: string | null): string {
  if (!id) return "Uncategorized";
  return CATEGORY_BY_ID[id]?.name ?? "Uncategorized";
}
